import 'package:get/get.dart';
import '../../../core/controllers/language_controller.dart';

class Surah {
  final int number;
  final String nameAr;
  final String nameFr;
  final String nameEn;
  final int ayahCount;
  final String revelationType;

  Surah({
    required this.number,
    required this.nameAr,
    required this.nameFr,
    required this.nameEn,
    required this.ayahCount,
    required this.revelationType,
  });

  factory Surah.fromJson(Map<String, dynamic> json) {
    return Surah(
      number: json['number'] ?? 0,
      nameAr: json['name_ar'] ?? '',
      nameFr: json['name_fr'] ?? '',
      nameEn: json['name_en'] ?? '',
      ayahCount: json['ayah_count'] ?? 0,
      revelationType: json['revelation_type'] ?? 'meccan',
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'number': number,
      'name_ar': nameAr,
      'name_fr': nameFr,
      'name_en': nameEn,
      'ayah_count': ayahCount,
      'revelation_type': revelationType,
    };
  }

  // Get translated name based on current language
  String get translatedName {
    final langController = Get.find<LanguageController>();
    switch (langController.currentLang) {
      case 'ar':
        return nameAr;
      case 'en':
        return nameEn;
      case 'fr':
      default:
        return nameFr;
    }
  }

  // Get translated revelation type
  String get translatedRevelationType {
    return revelationType == 'meccan' ? 'Meccan'.trx : 'Medinan'.trx;
  }

  static List<Surah> generateDefaultSurahs() {
    return [
      Surah(
        number: 1,
        nameAr: 'الفاتحة',
        nameFr: 'L\'Ouverture',
        nameEn: 'Al-Fatiha',
        ayahCount: 7,
        revelationType: 'meccan',
      ),
      Surah(
        number: 2,
        nameAr: 'البقرة',
        nameFr: 'La Vache',
        nameEn: 'Al-Baqarah',
        ayahCount: 286,
        revelationType: 'medinan',
      ),
      Surah(
        number: 3,
        nameAr: 'آل عمران',
        nameFr: 'La Famille d\'Imran',
        nameEn: 'Ali \'Imran',
        ayahCount: 200,
        revelationType: 'medinan',
      ),
      Surah(
        number: 4,
        nameAr: 'النساء',
        nameFr: 'Les Femmes',
        nameEn: 'An-Nisa',
        ayahCount: 176,
        revelationType: 'medinan',
      ),
      Surah(
        number: 5,
        nameAr: 'المائدة',
        nameFr: 'La Table Servie',
        nameEn: 'Al-Ma\'idah',
        ayahCount: 120,
        revelationType: 'medinan',
      ),
      Surah(
        number: 6,
        nameAr: 'الأنعام',
        nameFr: 'Les Bestiaux',
        nameEn: 'Al-An\'am',
        ayahCount: 165,
        revelationType: 'meccan',
      ),
      Surah(
        number: 7,
        nameAr: 'الأعراف',
        nameFr: 'Al-A\'raf',
        nameEn: 'Al-A\'raf',
        ayahCount: 206,
        revelationType: 'meccan',
      ),
      Surah(
        number: 8,
        nameAr: 'الأنفال',
        nameFr: 'Le Butin',
        nameEn: 'Al-Anfal',
        ayahCount: 75,
        revelationType: 'medinan',
      ),
      Surah(
        number: 9,
        nameAr: 'التوبة',
        nameFr: 'Le Repentir',
        nameEn: 'At-Tawbah',
        ayahCount: 129,
        revelationType: 'medinan',
      ),
      Surah(
        number: 10,
        nameAr: 'يونس',
        nameFr: 'Jonas',
        nameEn: 'Yunus',
        ayahCount: 109,
        revelationType: 'meccan',
      ),
      Surah(
        number: 11,
        nameAr: 'هود',
        nameFr: 'Hud',
        nameEn: 'Hud',
        ayahCount: 123,
        revelationType: 'meccan',
      ),
      Surah(
        number: 12,
        nameAr: 'يوسف',
        nameFr: 'Joseph',
        nameEn: 'Yusuf',
        ayahCount: 111,
        revelationType: 'meccan',
      ),
      Surah(
        number: 13,
        nameAr: 'الرعد',
        nameFr: 'Le Tonnerre',
        nameEn: 'Ar-Ra\'d',
        ayahCount: 43,
        revelationType: 'medinan',
      ),
      Surah(
        number: 14,
        nameAr: 'ابراهيم',
        nameFr: 'Abraham',
        nameEn: 'Ibrahim',
        ayahCount: 52,
        revelationType: 'meccan',
      ),
      Surah(
        number: 15,
        nameAr: 'الحجر',
        nameFr: 'Al-Hijr',
        nameEn: 'Al-Hijr',
        ayahCount: 99,
        revelationType: 'meccan',
      ),
      Surah(
        number: 16,
        nameAr: 'النحل',
        nameFr: 'Les Abeilles',
        nameEn: 'An-Nahl',
        ayahCount: 128,
        revelationType: 'meccan',
      ),
      Surah(
        number: 17,
        nameAr: 'الإسراء',
        nameFr: 'Le Voyage Nocturne',
        nameEn: 'Al-Isra',
        ayahCount: 111,
        revelationType: 'meccan',
      ),
      Surah(
        number: 18,
        nameAr: 'الكهف',
        nameFr: 'La Caverne',
        nameEn: 'Al-Kahf',
        ayahCount: 110,
        revelationType: 'meccan',
      ),
      Surah(
        number: 19,
        nameAr: 'مريم',
        nameFr: 'Marie',
        nameEn: 'Maryam',
        ayahCount: 98,
        revelationType: 'meccan',
      ),
      Surah(
        number: 20,
        nameAr: 'طه',
        nameFr: 'Ta-Ha',
        nameEn: 'Taha',
        ayahCount: 135,
        revelationType: 'meccan',
      ),
      Surah(
        number: 21,
        nameAr: 'الأنبياء',
        nameFr: 'Les Prophètes',
        nameEn: 'Al-Anbya',
        ayahCount: 112,
        revelationType: 'meccan',
      ),
      Surah(
        number: 22,
        nameAr: 'الحج',
        nameFr: 'Le Pèlerinage',
        nameEn: 'Al-Hajj',
        ayahCount: 78,
        revelationType: 'medinan',
      ),
      Surah(
        number: 23,
        nameAr: 'المؤمنون',
        nameFr: 'Les Croyants',
        nameEn: 'Al-Mu\'minun',
        ayahCount: 118,
        revelationType: 'meccan',
      ),
      Surah(
        number: 24,
        nameAr: 'النور',
        nameFr: 'La Lumière',
        nameEn: 'An-Nur',
        ayahCount: 64,
        revelationType: 'medinan',
      ),
      Surah(
        number: 25,
        nameAr: 'الفرقان',
        nameFr: 'Le Discernement',
        nameEn: 'Al-Furqan',
        ayahCount: 77,
        revelationType: 'meccan',
      ),
      Surah(
        number: 26,
        nameAr: 'الشعراء',
        nameFr: 'Les Poètes',
        nameEn: 'Ash-Shu\'ara',
        ayahCount: 227,
        revelationType: 'meccan',
      ),
      Surah(
        number: 27,
        nameAr: 'النمل',
        nameFr: 'Les Fourmis',
        nameEn: 'An-Naml',
        ayahCount: 93,
        revelationType: 'meccan',
      ),
      Surah(
        number: 28,
        nameAr: 'القصص',
        nameFr: 'Le Récit',
        nameEn: 'Al-Qasas',
        ayahCount: 88,
        revelationType: 'meccan',
      ),
      Surah(
        number: 29,
        nameAr: 'العنكبوت',
        nameFr: 'L\'Araignée',
        nameEn: 'Al-\'Ankabut',
        ayahCount: 69,
        revelationType: 'meccan',
      ),
      Surah(
        number: 30,
        nameAr: 'الروم',
        nameFr: 'Les Romains',
        nameEn: 'Ar-Rum',
        ayahCount: 60,
        revelationType: 'meccan',
      ),
      Surah(
        number: 31,
        nameAr: 'لقمان',
        nameFr: 'Luqman',
        nameEn: 'Luqman',
        ayahCount: 34,
        revelationType: 'meccan',
      ),
      Surah(
        number: 32,
        nameAr: 'السجدة',
        nameFr: 'La Prosternation',
        nameEn: 'As-Sajdah',
        ayahCount: 30,
        revelationType: 'meccan',
      ),
      Surah(
        number: 33,
        nameAr: 'الأحزاب',
        nameFr: 'Les Coalisés',
        nameEn: 'Al-Ahzab',
        ayahCount: 73,
        revelationType: 'medinan',
      ),
      Surah(
        number: 34,
        nameAr: 'سبأ',
        nameFr: 'Saba',
        nameEn: 'Saba',
        ayahCount: 54,
        revelationType: 'meccan',
      ),
      Surah(
        number: 35,
        nameAr: 'فاطر',
        nameFr: 'Le Créateur',
        nameEn: 'Fatir',
        ayahCount: 45,
        revelationType: 'meccan',
      ),
      Surah(
        number: 36,
        nameAr: 'يس',
        nameFr: 'Ya-Sin',
        nameEn: 'Ya-Sin',
        ayahCount: 83,
        revelationType: 'meccan',
      ),
      Surah(
        number: 37,
        nameAr: 'الصافات',
        nameFr: 'Les Rangs',
        nameEn: 'As-Saffat',
        ayahCount: 182,
        revelationType: 'meccan',
      ),
      Surah(
        number: 38,
        nameAr: 'ص',
        nameFr: 'Sad',
        nameEn: 'Sad',
        ayahCount: 88,
        revelationType: 'meccan',
      ),
      Surah(
        number: 39,
        nameAr: 'الزمر',
        nameFr: 'Les Groupes',
        nameEn: 'Az-Zumar',
        ayahCount: 75,
        revelationType: 'meccan',
      ),
      Surah(
        number: 40,
        nameAr: 'غافر',
        nameFr: 'Le Pardonneur',
        nameEn: 'Ghafir',
        ayahCount: 85,
        revelationType: 'meccan',
      ),
      Surah(
        number: 41,
        nameAr: 'فصلت',
        nameFr: 'Les Versets Détaillés',
        nameEn: 'Fussilat',
        ayahCount: 54,
        revelationType: 'meccan',
      ),
      Surah(
        number: 42,
        nameAr: 'الشورى',
        nameFr: 'La Consultation',
        nameEn: 'Ash-Shuraa',
        ayahCount: 53,
        revelationType: 'meccan',
      ),
      Surah(
        number: 43,
        nameAr: 'الزخرف',
        nameFr: 'L\'Ornement',
        nameEn: 'Az-Zukhruf',
        ayahCount: 89,
        revelationType: 'meccan',
      ),
      Surah(
        number: 44,
        nameAr: 'الدخان',
        nameFr: 'La Fumée',
        nameEn: 'Ad-Dukhan',
        ayahCount: 59,
        revelationType: 'meccan',
      ),
      Surah(
        number: 45,
        nameAr: 'الجاثية',
        nameFr: 'L\'Agenouillée',
        nameEn: 'Al-Jathiyah',
        ayahCount: 37,
        revelationType: 'meccan',
      ),
      Surah(
        number: 46,
        nameAr: 'الأحقاف',
        nameFr: 'Al-Ahqaf',
        nameEn: 'Al-Ahqaf',
        ayahCount: 35,
        revelationType: 'meccan',
      ),
      Surah(
        number: 47,
        nameAr: 'محمد',
        nameFr: 'Muhammad',
        nameEn: 'Muhammad',
        ayahCount: 38,
        revelationType: 'medinan',
      ),
      Surah(
        number: 48,
        nameAr: 'الفتح',
        nameFr: 'La Victoire',
        nameEn: 'Al-Fath',
        ayahCount: 29,
        revelationType: 'medinan',
      ),
      Surah(
        number: 49,
        nameAr: 'الحجرات',
        nameFr: 'Les Appartements',
        nameEn: 'Al-Hujurat',
        ayahCount: 18,
        revelationType: 'medinan',
      ),
      Surah(
        number: 50,
        nameAr: 'ق',
        nameFr: 'Qaf',
        nameEn: 'Qaf',
        ayahCount: 45,
        revelationType: 'meccan',
      ),
      Surah(
        number: 51,
        nameAr: 'الذاريات',
        nameFr: 'Qui Éparpillent',
        nameEn: 'Adh-Dhariyat',
        ayahCount: 60,
        revelationType: 'meccan',
      ),
      Surah(
        number: 52,
        nameAr: 'الطور',
        nameFr: 'Le Mont',
        nameEn: 'At-Tur',
        ayahCount: 49,
        revelationType: 'meccan',
      ),
      Surah(
        number: 53,
        nameAr: 'النجم',
        nameFr: 'L\'Étoile',
        nameEn: 'An-Najm',
        ayahCount: 62,
        revelationType: 'meccan',
      ),
      Surah(
        number: 54,
        nameAr: 'القمر',
        nameFr: 'La Lune',
        nameEn: 'Al-Qamar',
        ayahCount: 55,
        revelationType: 'meccan',
      ),
      Surah(
        number: 55,
        nameAr: 'الرحمن',
        nameFr: 'Le Tout Miséricordieux',
        nameEn: 'Ar-Rahman',
        ayahCount: 78,
        revelationType: 'medinan',
      ),
      Surah(
        number: 56,
        nameAr: 'الواقعة',
        nameFr: 'L\'Inévitable',
        nameEn: 'Al-Waqi\'ah',
        ayahCount: 96,
        revelationType: 'meccan',
      ),
      Surah(
        number: 57,
        nameAr: 'الحديد',
        nameFr: 'Le Fer',
        nameEn: 'Al-Hadid',
        ayahCount: 29,
        revelationType: 'medinan',
      ),
      Surah(
        number: 58,
        nameAr: 'المجادلة',
        nameFr: 'La Discussion',
        nameEn: 'Al-Mujadila',
        ayahCount: 22,
        revelationType: 'medinan',
      ),
      Surah(
        number: 59,
        nameAr: 'الحشر',
        nameFr: 'L\'Exode',
        nameEn: 'Al-Hashr',
        ayahCount: 24,
        revelationType: 'medinan',
      ),
      Surah(
        number: 60,
        nameAr: 'الممتحنة',
        nameFr: 'L\'Éprouvée',
        nameEn: 'Al-Mumtahanah',
        ayahCount: 13,
        revelationType: 'medinan',
      ),
      Surah(
        number: 61,
        nameAr: 'الصف',
        nameFr: 'Le Rang',
        nameEn: 'As-Saff',
        ayahCount: 14,
        revelationType: 'medinan',
      ),
      Surah(
        number: 62,
        nameAr: 'الجمعة',
        nameFr: 'Le Vendredi',
        nameEn: 'Al-Jumu\'ah',
        ayahCount: 11,
        revelationType: 'medinan',
      ),
      Surah(
        number: 63,
        nameAr: 'المنافقون',
        nameFr: 'Les Hypocrites',
        nameEn: 'Al-Munafiqun',
        ayahCount: 11,
        revelationType: 'medinan',
      ),
      Surah(
        number: 64,
        nameAr: 'التغابن',
        nameFr: 'La Grande Perte',
        nameEn: 'At-Taghabun',
        ayahCount: 18,
        revelationType: 'medinan',
      ),
      Surah(
        number: 65,
        nameAr: 'الطلاق',
        nameFr: 'Le Divorce',
        nameEn: 'At-Talaq',
        ayahCount: 12,
        revelationType: 'medinan',
      ),
      Surah(
        number: 66,
        nameAr: 'التحريم',
        nameFr: 'L\'Interdiction',
        nameEn: 'At-Tahrim',
        ayahCount: 12,
        revelationType: 'medinan',
      ),
      Surah(
        number: 67,
        nameAr: 'الملك',
        nameFr: 'La Royauté',
        nameEn: 'Al-Mulk',
        ayahCount: 30,
        revelationType: 'meccan',
      ),
      Surah(
        number: 68,
        nameAr: 'القلم',
        nameFr: 'La Plume',
        nameEn: 'Al-Qalam',
        ayahCount: 52,
        revelationType: 'meccan',
      ),
      Surah(
        number: 69,
        nameAr: 'الحاقة',
        nameFr: 'Celle qui Montre la Vérité',
        nameEn: 'Al-Haqqah',
        ayahCount: 52,
        revelationType: 'meccan',
      ),
      Surah(
        number: 70,
        nameAr: 'المعارج',
        nameFr: 'Les Voies d\'Ascension',
        nameEn: 'Al-Ma\'arij',
        ayahCount: 44,
        revelationType: 'meccan',
      ),
      Surah(
        number: 71,
        nameAr: 'نوح',
        nameFr: 'Noé',
        nameEn: 'Nuh',
        ayahCount: 28,
        revelationType: 'meccan',
      ),
      Surah(
        number: 72,
        nameAr: 'الجن',
        nameFr: 'Les Djinns',
        nameEn: 'Al-Jinn',
        ayahCount: 28,
        revelationType: 'meccan',
      ),
      Surah(
        number: 73,
        nameAr: 'المزمل',
        nameFr: 'L\'Enveloppé',
        nameEn: 'Al-Muzzammil',
        ayahCount: 20,
        revelationType: 'meccan',
      ),
      Surah(
        number: 74,
        nameAr: 'المدثر',
        nameFr: 'Le Revêtu d\'un Manteau',
        nameEn: 'Al-Muddaththir',
        ayahCount: 56,
        revelationType: 'meccan',
      ),
      Surah(
        number: 75,
        nameAr: 'القيامة',
        nameFr: 'La Résurrection',
        nameEn: 'Al-Qiyamah',
        ayahCount: 40,
        revelationType: 'meccan',
      ),
      Surah(
        number: 76,
        nameAr: 'الانسان',
        nameFr: 'L\'Homme',
        nameEn: 'Al-Insan',
        ayahCount: 31,
        revelationType: 'medinan',
      ),
      Surah(
        number: 77,
        nameAr: 'المرسلات',
        nameFr: 'Les Envoyés',
        nameEn: 'Al-Mursalat',
        ayahCount: 50,
        revelationType: 'meccan',
      ),
      Surah(
        number: 78,
        nameAr: 'النبأ',
        nameFr: 'La Nouvelle',
        nameEn: 'An-Naba',
        ayahCount: 40,
        revelationType: 'meccan',
      ),
      Surah(
        number: 79,
        nameAr: 'النازعات',
        nameFr: 'Ceux qui Arrachent',
        nameEn: 'An-Nazi\'at',
        ayahCount: 46,
        revelationType: 'meccan',
      ),
      Surah(
        number: 80,
        nameAr: 'عبس',
        nameFr: 'Il s\'est Renfrogné',
        nameEn: '\'Abasa',
        ayahCount: 42,
        revelationType: 'meccan',
      ),
      Surah(
        number: 81,
        nameAr: 'التكوير',
        nameFr: 'L\'Obscurcissement',
        nameEn: 'At-Takwir',
        ayahCount: 29,
        revelationType: 'meccan',
      ),
      Surah(
        number: 82,
        nameAr: 'الإنفطار',
        nameFr: 'La Rupture',
        nameEn: 'Al-Infitar',
        ayahCount: 19,
        revelationType: 'meccan',
      ),
      Surah(
        number: 83,
        nameAr: 'المطففين',
        nameFr: 'Les Fraudeurs',
        nameEn: 'Al-Mutaffifin',
        ayahCount: 36,
        revelationType: 'meccan',
      ),
      Surah(
        number: 84,
        nameAr: 'الإنشقاق',
        nameFr: 'La Déchirure',
        nameEn: 'Al-Inshiqaq',
        ayahCount: 25,
        revelationType: 'meccan',
      ),
      Surah(
        number: 85,
        nameAr: 'البروج',
        nameFr: 'Les Constellations',
        nameEn: 'Al-Buruj',
        ayahCount: 22,
        revelationType: 'meccan',
      ),
      Surah(
        number: 86,
        nameAr: 'الطارق',
        nameFr: 'L\'Astre Nocturne',
        nameEn: 'At-Tariq',
        ayahCount: 17,
        revelationType: 'meccan',
      ),
      Surah(
        number: 87,
        nameAr: 'الأعلى',
        nameFr: 'Le Très-Haut',
        nameEn: 'Al-A\'la',
        ayahCount: 19,
        revelationType: 'meccan',
      ),
      Surah(
        number: 88,
        nameAr: 'الغاشية',
        nameFr: 'L\'Enveloppante',
        nameEn: 'Al-Ghashiyah',
        ayahCount: 26,
        revelationType: 'meccan',
      ),
      Surah(
        number: 89,
        nameAr: 'الفجر',
        nameFr: 'L\'Aube',
        nameEn: 'Al-Fajr',
        ayahCount: 30,
        revelationType: 'meccan',
      ),
      Surah(
        number: 90,
        nameAr: 'البلد',
        nameFr: 'La Cité',
        nameEn: 'Al-Balad',
        ayahCount: 20,
        revelationType: 'meccan',
      ),
      Surah(
        number: 91,
        nameAr: 'الشمس',
        nameFr: 'Le Soleil',
        nameEn: 'Ash-Shams',
        ayahCount: 15,
        revelationType: 'meccan',
      ),
      Surah(
        number: 92,
        nameAr: 'الليل',
        nameFr: 'La Nuit',
        nameEn: 'Al-Layl',
        ayahCount: 21,
        revelationType: 'meccan',
      ),
      Surah(
        number: 93,
        nameAr: 'الضحى',
        nameFr: 'Le Jour Montant',
        nameEn: 'Ad-Duhaa',
        ayahCount: 11,
        revelationType: 'meccan',
      ),
      Surah(
        number: 94,
        nameAr: 'الشرح',
        nameFr: 'L\'Ouverture',
        nameEn: 'Ash-Sharh',
        ayahCount: 8,
        revelationType: 'meccan',
      ),
      Surah(
        number: 95,
        nameAr: 'التين',
        nameFr: 'Le Figuier',
        nameEn: 'At-Tin',
        ayahCount: 8,
        revelationType: 'meccan',
      ),
      Surah(
        number: 96,
        nameAr: 'العلق',
        nameFr: 'L\'Adhérence',
        nameEn: 'Al-\'Alaq',
        ayahCount: 19,
        revelationType: 'meccan',
      ),
      Surah(
        number: 97,
        nameAr: 'القدر',
        nameFr: 'La Destinée',
        nameEn: 'Al-Qadr',
        ayahCount: 5,
        revelationType: 'meccan',
      ),
      Surah(
        number: 98,
        nameAr: 'البينة',
        nameFr: 'La Preuve',
        nameEn: 'Al-Bayyinah',
        ayahCount: 8,
        revelationType: 'medinan',
      ),
      Surah(
        number: 99,
        nameAr: 'الزلزلة',
        nameFr: 'Le Séisme',
        nameEn: 'Az-Zalzalah',
        ayahCount: 8,
        revelationType: 'medinan',
      ),
      Surah(
        number: 100,
        nameAr: 'العاديات',
        nameFr: 'Les Coursiers',
        nameEn: 'Al-\'Adiyat',
        ayahCount: 11,
        revelationType: 'meccan',
      ),
      Surah(
        number: 101,
        nameAr: 'القارعة',
        nameFr: 'Le Fracas',
        nameEn: 'Al-Qari\'ah',
        ayahCount: 11,
        revelationType: 'meccan',
      ),
      Surah(
        number: 102,
        nameAr: 'التكاثر',
        nameFr: 'La Course aux Richesses',
        nameEn: 'At-Takathur',
        ayahCount: 8,
        revelationType: 'meccan',
      ),
      Surah(
        number: 103,
        nameAr: 'العصر',
        nameFr: 'Le Temps',
        nameEn: 'Al-\'Asr',
        ayahCount: 3,
        revelationType: 'meccan',
      ),
      Surah(
        number: 104,
        nameAr: 'الهمزة',
        nameFr: 'Les Calomniateurs',
        nameEn: 'Al-Humazah',
        ayahCount: 9,
        revelationType: 'meccan',
      ),
      Surah(
        number: 105,
        nameAr: 'الفيل',
        nameFr: 'L\'Éléphant',
        nameEn: 'Al-Fil',
        ayahCount: 5,
        revelationType: 'meccan',
      ),
      Surah(
        number: 106,
        nameAr: 'قريش',
        nameFr: 'Quraysh',
        nameEn: 'Quraysh',
        ayahCount: 4,
        revelationType: 'meccan',
      ),
      Surah(
        number: 107,
        nameAr: 'الماعون',
        nameFr: 'L\'Ustensile',
        nameEn: 'Al-Ma\'un',
        ayahCount: 7,
        revelationType: 'meccan',
      ),
      Surah(
        number: 108,
        nameAr: 'الكوثر',
        nameFr: 'L\'Abondance',
        nameEn: 'Al-Kawthar',
        ayahCount: 3,
        revelationType: 'meccan',
      ),
      Surah(
        number: 109,
        nameAr: 'الكافرون',
        nameFr: 'Les Infidèles',
        nameEn: 'Al-Kafirun',
        ayahCount: 6,
        revelationType: 'meccan',
      ),
      Surah(
        number: 110,
        nameAr: 'النصر',
        nameFr: 'Le Secours',
        nameEn: 'An-Nasr',
        ayahCount: 3,
        revelationType: 'medinan',
      ),
      Surah(
        number: 111,
        nameAr: 'المسد',
        nameFr: 'Les Fibres',
        nameEn: 'Al-Masad',
        ayahCount: 5,
        revelationType: 'meccan',
      ),
      Surah(
        number: 112,
        nameAr: 'الإخلاص',
        nameFr: 'Le Monothéisme Pur',
        nameEn: 'Al-Ikhlas',
        ayahCount: 4,
        revelationType: 'meccan',
      ),
      Surah(
        number: 113,
        nameAr: 'الفلق',
        nameFr: 'L\'Aube Naissante',
        nameEn: 'Al-Falaq',
        ayahCount: 5,
        revelationType: 'meccan',
      ),
      Surah(
        number: 114,
        nameAr: 'الناس',
        nameFr: 'Les Gens',
        nameEn: 'An-Nas',
        ayahCount: 6,
        revelationType: 'meccan',
      ),
    ];
  }
}
